/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Nomenclatures;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NomenclaturesRecord extends UpdatableRecordImpl<NomenclaturesRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 1335386305;

    /**
     * Setter for <code>public.nomenclatures.name</code>.
     */
    public NomenclaturesRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.nomenclatures.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.nomenclatures.code</code>.
     */
    public NomenclaturesRecord setCode(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.nomenclatures.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Nomenclatures.NOMENCLATURES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Nomenclatures.NOMENCLATURES.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NomenclaturesRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NomenclaturesRecord value2(Integer value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NomenclaturesRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NomenclaturesRecord
     */
    public NomenclaturesRecord() {
        super(Nomenclatures.NOMENCLATURES);
    }

    /**
     * Create a detached, initialised NomenclaturesRecord
     */
    public NomenclaturesRecord(String name, Integer code) {
        super(Nomenclatures.NOMENCLATURES);

        set(0, name);
        set(1, code);
    }
}
