/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybillpositions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillpositionsRecord extends UpdatableRecordImpl<WaybillpositionsRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -118531475;

    /**
     * Setter for <code>public.waybillpositions.id</code>.
     */
    public WaybillpositionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillpositions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.waybillpositions.price</code>.
     */
    public WaybillpositionsRecord setPrice(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillpositions.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.waybillpositions.nomenclature</code>.
     */
    public WaybillpositionsRecord setNomenclature(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillpositions.nomenclature</code>.
     */
    public String getNomenclature() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.waybillpositions.quantity</code>.
     */
    public WaybillpositionsRecord setQuantity(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillpositions.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.waybillpositions.waybillid</code>.
     */
    public WaybillpositionsRecord setWaybillid(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillpositions.waybillid</code>.
     */
    public Integer getWaybillid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Waybillpositions.WAYBILLPOSITIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Waybillpositions.WAYBILLPOSITIONS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Waybillpositions.WAYBILLPOSITIONS.NOMENCLATURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Waybillpositions.WAYBILLPOSITIONS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Waybillpositions.WAYBILLPOSITIONS.WAYBILLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNomenclature();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getWaybillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNomenclature();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWaybillid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord value2(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord value3(String value) {
        setNomenclature(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord value5(Integer value) {
        setWaybillid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionsRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillpositionsRecord
     */
    public WaybillpositionsRecord() {
        super(Waybillpositions.WAYBILLPOSITIONS);
    }

    /**
     * Create a detached, initialised WaybillpositionsRecord
     */
    public WaybillpositionsRecord(Integer id, Integer price, String nomenclature, Integer quantity, Integer waybillid) {
        super(Waybillpositions.WAYBILLPOSITIONS);

        set(0, id);
        set(1, price);
        set(2, nomenclature);
        set(3, quantity);
        set(4, waybillid);
    }
}
