/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = 938649447;

    private final String  organization;
    private final Integer inn;
    private final Integer checking;

    public Organizations(Organizations value) {
        this.organization = value.organization;
        this.inn = value.inn;
        this.checking = value.checking;
    }

    public Organizations(
        String  organization,
        Integer inn,
        Integer checking
    ) {
        this.organization = organization;
        this.inn = inn;
        this.checking = checking;
    }

    public String getOrganization() {
        return this.organization;
    }

    public Integer getInn() {
        return this.inn;
    }

    public Integer getChecking() {
        return this.checking;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(organization);
        sb.append(", ").append(inn);
        sb.append(", ").append(checking);

        sb.append(")");
        return sb.toString();
    }
}
