/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybill implements Serializable {

    private static final long serialVersionUID = -1994693305;

    private final Integer id;
    private final Date    date;
    private final String  organization;

    public Waybill(Waybill value) {
        this.id = value.id;
        this.date = value.date;
        this.organization = value.organization;
    }

    public Waybill(
        Integer id,
        Date    date,
        String  organization
    ) {
        this.id = id;
        this.date = date;
        this.organization = organization;
    }

    public Integer getId() {
        return this.id;
    }

    public Date getDate() {
        return this.date;
    }

    public String getOrganization() {
        return this.organization;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybill (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(organization);

        sb.append(")");
        return sb.toString();
    }
}
