/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybillpositions implements Serializable {

    private static final long serialVersionUID = -908815838;

    private final Integer id;
    private final Integer price;
    private final String  nomenclature;
    private final Integer quantity;
    private final Integer waybillid;

    public Waybillpositions(Waybillpositions value) {
        this.id = value.id;
        this.price = value.price;
        this.nomenclature = value.nomenclature;
        this.quantity = value.quantity;
        this.waybillid = value.waybillid;
    }

    public Waybillpositions(
        Integer id,
        Integer price,
        String  nomenclature,
        Integer quantity,
        Integer waybillid
    ) {
        this.id = id;
        this.price = price;
        this.nomenclature = nomenclature;
        this.quantity = quantity;
        this.waybillid = waybillid;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getPrice() {
        return this.price;
    }

    public String getNomenclature() {
        return this.nomenclature;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public Integer getWaybillid() {
        return this.waybillid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybillpositions (");

        sb.append(id);
        sb.append(", ").append(price);
        sb.append(", ").append(nomenclature);
        sb.append(", ").append(quantity);
        sb.append(", ").append(waybillid);

        sb.append(")");
        return sb.toString();
    }
}
