/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Nomenclatures;
import db.tables.Organizations;
import db.tables.Waybill;
import db.tables.Waybillpositions;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index NOMENCLATURES_PKEY = Indexes0.NOMENCLATURES_PKEY;
    public static final Index ORGANIZATIONS_PKEY = Indexes0.ORGANIZATIONS_PKEY;
    public static final Index WAYBILL_PKEY = Indexes0.WAYBILL_PKEY;
    public static final Index WAYBILLPOSITIONS_PKEY = Indexes0.WAYBILLPOSITIONS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index NOMENCLATURES_PKEY = Internal.createIndex("nomenclatures_pkey", Nomenclatures.NOMENCLATURES, new OrderField[] { Nomenclatures.NOMENCLATURES.NAME }, true);
        public static Index ORGANIZATIONS_PKEY = Internal.createIndex("organizations_pkey", Organizations.ORGANIZATIONS, new OrderField[] { Organizations.ORGANIZATIONS.ORGANIZATION }, true);
        public static Index WAYBILL_PKEY = Internal.createIndex("waybill_pkey", Waybill.WAYBILL, new OrderField[] { Waybill.WAYBILL.ID }, true);
        public static Index WAYBILLPOSITIONS_PKEY = Internal.createIndex("waybillpositions_pkey", Waybillpositions.WAYBILLPOSITIONS, new OrderField[] { Waybillpositions.WAYBILLPOSITIONS.ID }, true);
    }
}
