/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Nomenclatures;
import db.tables.Organizations;
import db.tables.Waybill;
import db.tables.Waybillpositions;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2007726095;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.nomenclatures</code>.
     */
    public final Nomenclatures NOMENCLATURES = db.tables.Nomenclatures.NOMENCLATURES;

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = db.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.waybill</code>.
     */
    public final Waybill WAYBILL = db.tables.Waybill.WAYBILL;

    /**
     * The table <code>public.waybillpositions</code>.
     */
    public final Waybillpositions WAYBILLPOSITIONS = db.tables.Waybillpositions.WAYBILLPOSITIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Nomenclatures.NOMENCLATURES,
            Organizations.ORGANIZATIONS,
            Waybill.WAYBILL,
            Waybillpositions.WAYBILLPOSITIONS);
    }
}
