/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Nomenclatures;
import db.tables.Organizations;
import db.tables.Waybill;
import db.tables.Waybillpositions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.nomenclatures</code>.
     */
    public static final Nomenclatures NOMENCLATURES = db.tables.Nomenclatures.NOMENCLATURES;

    /**
     * The table <code>public.organizations</code>.
     */
    public static final Organizations ORGANIZATIONS = db.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.waybill</code>.
     */
    public static final Waybill WAYBILL = db.tables.Waybill.WAYBILL;

    /**
     * The table <code>public.waybillpositions</code>.
     */
    public static final Waybillpositions WAYBILLPOSITIONS = db.tables.Waybillpositions.WAYBILLPOSITIONS;
}
